### PR TITLE
Add method to output mpd as a string, and associated test

### PR DESCRIPTION
**Pull request by davemevans**
I'm using python-mpegdash to do some simple transformation of a manifest before forwarding elsewhere for consumption. Currently python-mpegdash can only output to a file, but it seems overkill for me to create a temporary file for writing the output, only to immediately re-read the contents.

This patch adds xml string output to the parser.

The test is convoluted and a bit pointless, but proves the output is reversable and repeatable.

### CODE REVIEW

**Comment by sangwonl** [comment]
@davemevans thanks for your endless contribution.

The ci test result in this PR is saying. It's because python2.6 test limitation on max diff string of `assertEqual`. You can add `self.maxDiff = None` for the test case class.

```
======================================================================
FAIL: test_mpd2xmlstr (test_mpdtoxml.MPD2XMLTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/caststack/python-mpegdash/tests/test_mpdtoxml.py", line 42, in test_mpd2xmlstr
    self.assertEqual(xmlstrout, xmlstrout2)
AssertionError: '<?xm[188 chars]     ad/\n        </BaseURL>\n        <Adaptat[3031 chars]D>\n' != '<?xm[188 chars]     \n            ad/\n        \n        </Ba[3303 chars]D>\n'
Diff is 3640 characters long. Set self.maxDiff to None to see it.
```

**Comment by davemevans** [comment]
I'll take a look when I have a minute, though I don't have a Python 2.6 env to test in.

To be honest, the test is fairly pointless so the answer may just be to remove it 😉

**Comment by davemevans** [comment]
Hmm, so it looks like there is some additional whitespace added around text content in Python 2.6 only. I'll have a think.

**Comment by davemevans** [comment]
minidom's `writexml` changed between 2.6 and 2.7 - compare https://github.com/python/cpython/blob/2.6/Lib/xml/dom/minidom.py#L814 and https://github.com/python/cpython/blob/2.7/Lib/xml/dom/minidom.py#L806 - causing this behaviour.

I'll try to figure out some workaround ...

**Comment by davemevans** [comment]
OK, tests now pass! 🎉 Please take a look.

Apologies for the large number of commits - might be worth squashing on commit 😉

**Pull request merged**
